
{
  parserClass="com.jivesoftware.robot.intellij.plugin.parser.RobotParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Robot"
  psiImplClassSuffix="Impl"
  psiPackage="com.jivesoftware.robot.intellij.plugin.psi"
  psiImplPackage="com.jivesoftware.robot.intellij.plugin.psi.impl"

  elementTypeHolderClass="com.jivesoftware.robot.intellij.plugin.parser.RobotTypes"
  elementTypeClass="com.jivesoftware.robot.intellij.plugin.parser.RobotElementType"
  tokenTypeClass="com.jivesoftware.robot.intellij.plugin.lexer.RobotToken"

  psiImplUtilClass="com.jivesoftware.robot.intellij.plugin.elements.RobotImplUtil"
}

robotFile ::= item*

private item ::= (KEYWORD_EL|KEYWORD_DEF_EL|OTHER_EL)

KEYWORD_EL ::= ROBOT_KEYWORD_TOKEN {mixin="com.jivesoftware.robot.intellij.plugin.elements.references.RobotNamedElementImpl"
                                          implements="com.jivesoftware.robot.intellij.plugin.elements.references.RobotNamedElement"
                                          methods=[getName setName getNameIdentifier getReference getReferences]}

OTHER_EL ::= (TEST_CASES_TABLE_HEADING_TOKEN|KEYWORDS_TABLE_HEADING_TOKEN|TABLE_HEADING_TOKEN|TEST_CASE_HEADER_TOKEN|ROBOT_KEYWORD_ARG_TOKEN
                        |COMMENT_TOKEN|VARIABLE_TOKEN|ASSIGNMENT_TOKEN|META_INFO_TOKEN|NUMBER_LITERAL_TOKEN|COLUMN_SEP_TOKEN|SINGLE_SPACE_TOKEN|NEWLINE_TOKEN
                        |TAG_TOKEN|DOCUMENTATION_TOKEN)

KEYWORD_DEF_EL ::= ROBOT_KEYWORD_DEF_TOKEN {mixin="com.jivesoftware.robot.intellij.plugin.elements.references.RobotNamedElementImpl"
                                                  implements="com.jivesoftware.robot.intellij.plugin.elements.references.RobotNamedElement"
                                                  methods=[getName setName getNameIdentifier getPresentation]}

ERROR_EL ::= BAD_CHAR_TOKEN